service:
    name: harness_guestbook
    identifier: harnessguestbook
    serviceDefinition:
        type: Kubernetes
        spec:
            manifests:
                - manifest:
                    identifier: guestbook
                    type: K8sManifest
                    spec:
                      store:
                        type: Github
                        spec:
                            connectorRef: harnessgitconnector
                            gitFetchType: Branch
                            paths:
                                - k8s-manifests/guestbook-ui-deployment.yaml
                                - k8s-manifests/guestbook-ui-svc.yaml
                            branch: main
                        skipResourceVersioning: false
                        enableDeclarativeRollback: false
    gitOpsEnabled: false
